date_loop: properly implement YYYY, MM, etc. as fully functional variables, supporting string substitution and the like; rename all local variables to '__<var>__'

diff --git a/date_loop b/date_loop
--- a/date_loop
+++ b/date_loop
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-usage="usage: $0 START END INCREMENT COMMAND [-v]
+__usage__="usage: ${0} START END INCREMENT COMMAND [-v]
 
 Loop over a range of dates (UTC) in steps increments of multiples of hours.
 
@@ -24,166 +24,158 @@ Optional arguments:
     -p N
         Parallelize over N processes at a time (N in [1..99]).
 "
-debug=false
+__debug__=false
 
 # Set defaults
-verbose=false
+__verbose__=false
 
 # Parse command line arguments
-i=0
-n=0
-num_procs=1
-args=("${@}")
-for ((i = 0; i < ${#args[@]}; i++))
+__n__=0
+__num_procs__=1
+__args__=("${@}")
+for ((__i__ = 0; __i__ < ${#__args__[@]}; __i__++))
 do
-    arg=${args[i]}
-    $debug && echo "${i} ${arg}" >&2
-    case "${arg}" in
+    __arg__=${__args__[__i__]}
+    ${__debug__} && echo "${__i__} ${__arg__}" >&2
+    case "${__arg__}" in
         "-v")
-            verbose=true
-            echo "${args[i+1]}" | grep -q '^[1-9][0-9]\{,2\}$'
-            [ ${?} -eq 0 ] && { i=$((i+1)); vb_n=${args[i]}; } || vb_n=1
+            __verbose__=true
+            echo "${__args__[__i__+1]}" | grep -q '^[1-9][0-9]\{,2\}$'
+            [ ${?} -eq 0 ] && { __i__=$((__i__+1)); __vb_n__=${__args__[__i__]}; } || __vb_n__=1
         ;;
         "-p")
-            echo "${args[i+1]}" | grep -q '^[1-9][0-9]\?$'
+            echo "${__args__[__i__+1]}" | grep -q '^[1-9][0-9]\?$'
             [ ${?} -ne 0 ] && { echo "'-p' not followed by number of processes" >&2; exit 4; }
-            i=$((i+1))
-            num_procs=${args[i]}
+            __i__=$((__i__+1))
+            __num_procs__=${__args__[__i__]}
         ;;
         *)
-            n=$((n+1))
-            case "${n}" in
-                1) date_start="${arg}" ;;
-                2) date_end="${arg}" ;;
-                3) increment="${arg}" ;;
-                4) cmd="${arg}" ;;
+            __n__=$((__n__+1))
+            case "${__n__}" in
+                1) __date_start__="${__arg__}" ;;
+                2) __date_end__="${__arg__}" ;;
+                3) __increment__="${__arg__}" ;;
+                4) __cmd__="${__arg__}" ;;
             esac
         ;;
     esac
 done
-[ ${n} -ne 4 ] && { echo -e "error: wrong number of positional arguments: ${n}\n\n${usage}" >&2; exit 2; }
+[ ${__n__} -ne 4 ] && { echo -e "error: wrong number of positional arguments: ${__n__}\n\n${__usage__}" >&2; exit 2; }
 
 # Set timezone to UTC to avoid winter-/summertime change issues
 export TZ=UTC
 
 # Determine resolution based on start date length
-case ${#date_start} in
-    10) res=hour;;
-    12) res=minute;;
-    *)  echo "invalid start datetime ${date_start} string of length ${#date_start}" >&2
+case ${#__date_start__} in
+    10) __res__=hour;;
+    12) __res__=minute;;
+    *)  echo "invalid start datetime ${__date_start__} string of length ${#__date_start__}" >&2
         exit 2
     ;;
 esac
 
 # Check dates and increment
-if [ "${res}" == "hour" ]
+if [ "${__res__}" == "hour" ]
 then
-    echo "${date_start}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
-    err="invalid start date ${date_start} for length 10, expect format YYYYMMDDHH, i.e., %Y%m%d%H"
+    echo "${__date_start__}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
+    err="invalid start date ${__date_start__} for length 10, expect format YYYYMMDDHH, i.e., %Y%m%d%H"
     [ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
-    echo "${date_end}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
-    err="invalid end date ${date_end} for length 10, expect format YYYYMMDDHH, i.e., %Y%m%d%H"
+    echo "${__date_end__}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9]'
+    err="invalid end date ${__date_end__} for length 10, expect format YYYYMMDDHH, i.e., %Y%m%d%H"
     [ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
-elif [ "${res}" == "minute" ]
+elif [ "${__res__}" == "minute" ]
 then
-    echo "${date_start}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9][0-5][0-9]'
-    err="invalid start date ${date_start} for length 12, expect format YYYYMMDDHHNN, i.e., %Y%m%d%H%M"
+    echo "${__date_start__}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9][0-5][0-9]'
+    err="invalid start date ${__date_start__} for length 12, expect format YYYYMMDDHHNN, i.e., %Y%m%d%H%M"
     [ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
-    echo "${date_end}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9][0-5][0-9]'
-    err="invalid end date ${date_end} for length 12, expect format YYYYMMDDHHNN, i.e., %Y%m%d%H%M"
+    echo "${__date_end__}" | grep -q '[12][0-9]\{3\}[01][0-9][0-3][0-9][012][0-9][0-5][0-9]'
+    err="invalid end date ${__date_end__} for length 12, expect format YYYYMMDDHHNN, i.e., %Y%m%d%H%M"
     [ $? -ne 0 ] && { echo "${err}" >&2; exit 2; }
 else
-    echo "invalid start date ${date_start} of length ${#date_start}" >&2; exit 2
+    echo "invalid start date ${__date_start__} of length ${#__date_start__}" >&2; exit 2
 fi
-err="invalid non-zero increment ${increment}"
-[ ${increment} -eq 0 ] && { echo "${err}" >&2; exit 2; }
+err="invalid non-zero increment ${__increment__}"
+[ ${__increment__} -eq 0 ] && { echo "${err}" >&2; exit 2; }
 
 # Determine start date
-case "${res}" in
-    "hour"  ) date_curr="$(TZ=UTC date +%Y%m%d%H   -d "${date_start:0:8} ${date_start:8:2} - ${increment} hours")" ;;
-    "minute") date_curr="$(TZ=UTC date +%Y%m%d%H%M -d "${date_start:0:8} ${date_start:8:4} - ${increment} minutes")" ;;
+case "${__res__}" in
+    "hour"  ) __date_curr__="$(TZ=UTC date +%Y%m%d%H   -d "${__date_start__:0:8} ${__date_start__:8:2} - ${__increment__} hours")" ;;
+    "minute") __date_curr__="$(TZ=UTC date +%Y%m%d%H%M -d "${__date_start__:0:8} ${__date_start__:8:4} - ${__increment__} minutes")" ;;
 esac
 
 # Loop over dates (dont use while loop to avoid infinite loop)
-pids_active=()
-dates_active=()
-iter_max=$((date_end - date_start)) # bigger than actual number of iterations
-for iter_i in $(seq 0 $iter_max)
+__pids_active__=()
+__dates_active__=()
+__iter_max__=$((__date_end__ - __date_start__)) # bigger than actual number of iterations
+for iter_i in $(seq 0 ${__iter_max__})
 do
     # Increment date
-    case "${res}" in
-        "hour"  ) date_curr="$(TZ=UTC date +%Y%m%d%H   -d "${date_curr:0:8} ${date_curr:8:2} + ${increment} hours")";;
-        "minute") date_curr="$(TZ=UTC date +%Y%m%d%H%M -d "${date_curr:0:8} ${date_curr:8:4} + ${increment} minutes")";;
+    case "${__res__}" in
+        "hour"  ) __date_curr__="$(TZ=UTC date +%Y%m%d%H   -d "${__date_curr__:0:8} ${__date_curr__:8:2} + ${__increment__} hours")";;
+        "minute") __date_curr__="$(TZ=UTC date +%Y%m%d%H%M -d "${__date_curr__:0:8} ${__date_curr__:8:4} + ${__increment__} minutes")";;
     esac
-    yyyy="${date_curr:0:4}"
-    mm="${date_curr:4:2}"
-    dd="${date_curr:6:2}"
-    hh="${date_curr:8:2}"
-    nn="${date_curr:10:2}"
 
     # Are we done yet?
-    [ ${date_curr} -gt ${date_end} ] && break
+    [ ${__date_curr__} -gt ${__date_end__} ] && break
 
-    # Insert date components in comment
-    cmd_i="$(echo ${cmd} | sed \
-            -e "s/\${\?DATE}\?/${date_curr}/g" \
-            -e "s/\${\?YYYY}\?/${yyyy}/g" \
-            -e "s/\${\?MM}\?/${mm}/g" \
-            -e "s/\${\?DD}\?/${dd}/g" \
-            -e "s/\${\?HH}\?/${hh}/g" \
-            -e "s/\${\?NN}\?/${nn}/g")"
+    # Define variables to access the datetime components
+    DATE="${__date_curr__}"
+    YYYY="${__date_curr__:0:4}"
+    MM="${__date_curr__:4:2}"
+    DD="${__date_curr__:6:2}"
+    HH="${__date_curr__:8:2}"
+    NN="${__date_curr__:10:2}"
 
     # Print current timestep if requested
-    ${verbose} && [ $((iter_i%vb_n)) -eq 0 ] && echo "${date_curr}"
+    ${__verbose__} && [ $((iter_i%__vb_n__)) -eq 0 ] && echo "${__date_curr__}"
 
     # Execute command
-    eval ${cmd_i} &
-    pids_active[iter_i%num_procs]=${!}
-    dates_active[iter_i%num_procs]=${date_curr}
+    eval ${__cmd__} &
+    __pids_active__[iter_i%__num_procs__]=${!}
+    __dates_active__[iter_i%__num_procs__]=${__date_curr__}
 
     # Once N processes have been started in the background,
     # wait for them to finish before starting new ones
     # For sequential execution, this is simply done every timestep
-    if [ $(((iter_i+1)%num_procs)) -eq 0 ]
+    if [ $(((iter_i+1)%__num_procs__)) -eq 0 ]
     then
         # Wait in turn for each active process
         # Count the number of failed processes
         # Even if one fails, the others can finish
-        nerr=0
-        stats=()
-        for (( i=0; i<${num_procs}; i++ ))
+        __nerr__=0
+        __stats__=()
+        for (( __i__=0; __i__<${__num_procs__}; __i__++ ))
         do
-            pid=${pids_active[i]}
-            date=${dates_active[i]}
-            wait ${pid}
-            stat=${?}
-            stats[i]=${stat}
-            [ ${stat} -ne 0 ] && nerr=$((nerr + 1))
+            __pid__=${__pids_active__[__i__]}
+            __date__=${__dates_active__[__i__]}
+            wait ${__pid__}
+            __stat__=${?}
+            __stats__[__i__]=${__stat__}
+            [ ${__stat__} -ne 0 ] && __nerr__=$((__nerr__ + 1))
         done
-        pics_active=()
 
         # Just in case
         wait
 
         # In case of failed processes, abort execution
-        if [ ${nerr} -gt 0 ]
+        if [ ${__nerr__} -gt 0 ]
         then
-            ierr=0
-            for (( i=0; i<${num_procs}; i++ ))
+            __ierr__=0
+            for (( __i__=0; __i__<${__num_procs__}; __i__++ ))
             do
-                pid=${pids_active[i]}
-                date=${dates_active[i]}
-                stat=${stats[i]}
-                echo -n " $((i+1))/${num_procs} [${pid}] "
-                if [ ${stat} -eq 0 ]
+                __pid__=${__pids_active__[__i__]}
+                __date__=${__dates_active__[__i__]}
+                __stat__=${__stats__[__i__]}
+                echo -n " $((__i__+1))/${__num_procs__} [${__pid__}] "
+                if [ ${__stat__} -eq 0 ]
                 then
-                    echo "OK ${date}" >&2
+                    echo "OK ${__date__}" >&2
                 else
-                    echo "ERROR $((ierr+1))/${nerr} (${stat}) ${date}" >&2
-                    ierr=$((ierr+1))
+                    echo "ERROR $((__ierr__+1))/${__nerr__} (${__stat__}) ${__date__}" >&2
+                    __ierr__=$((__ierr__+1))
                 fi
             done
-            exit ${nerr}
+            exit ${__nerr__}
         fi
     fi
 done
