date_loop: refine error messages

diff --git a/date_loop b/date_loop
--- a/date_loop
+++ b/date_loop
@@ -168,19 +168,21 @@ do
         # In case of failed processes, abort execution
         if [ ${nerr} -gt 0 ]
         then
+            ierr=0
             for (( i=0; i<${num_procs}; i++ ))
             do
                 pid=${pids_active[i]}
                 date=${dates_active[i]}
                 stat=${stats[i]}
+                echo -n " $((i+1))/${num_procs} [${pid}] "
                 if [ ${stat} -eq 0 ]
                 then
-                    echo "[${pid}] OK ${date}" >&2
+                    echo "OK ${date}" >&2
                 else
-                    echo "[${pid}] ERROR ${stat} ($((i+1))/${num_procs}) ${date}" >&2
+                    echo "ERROR $((ierr+1))/${nerr} (${stat}) ${date}" >&2
+                    ierr=$((ierr+1))
                 fi
             done
-            echo " ABORT ${nerr}/${num_procs}" >&2
             exit ${nerr}
         fi
     fi
