enhance script to toggle keyboard layout: add check for display availability and fix it for reattached tmux session

diff --git a/keylaytog b/keylaytog
--- a/keylaytog
+++ b/keylaytog
@@ -1,50 +1,90 @@
 #!/bin/bash
 #
-# keylaytog -- Toggle keyboard layout variant
+# keylaytog -- Toggle keyboard layout (us, us_intl)
 #
 
-layout=us
-variants=('' alt-intl)
 
-# Get current setup
-cur_layout=$(setxkbmap -query | \grep layout | awk '{print $2}')
-cur_variant=$(setxkbmap -query | \grep variant | awk '{print $2}')
+main()
+{
+    layouts=(us us_intl)
 
-# Determine new setup
-new_layout="${layout}"
-if [ "${cur_layout}" != "${new_layout}" ]
-then
-    # Different layout: use first variant
-    new_variant="${variants[0]}"
-else
-    # Same layout: cycle through variants
-    # Results in toggling for two variants
-    # If current variant is not found, default to first
-    n=${#variants[@]}
+    ensure_display_access
+    
+    # Get current setup
+    cur_layout=$(setxkbmap -query | \grep layout | awk '{print $2}')
+    
+    # Cycle through layouts (equal to toggling for two options)
+    # If current layout is not found, default to first
+    n=${#layouts[@]}
     new_i=0
     for i in $(seq 0 $((n - 1)))
     do
-        variant_i="${variants[$i]}"
-        if [ "${cur_variant}" == "${variant_i}" ]
+        layout_i="${layouts[$i]}"
+        if [ "${cur_layout}" == "${layout_i}" ]
         then
-            # Current variant found: select next variant
+            # Current layout found: select next layout
             # If the current is the last, stick with the
             # first, otherwise select the next one
             [ ${i} -lt $((n - 1)) ] && new_i=$((i + 1))
             break
         fi
     done
-    new_variant="${variants[$new_i]}"
-fi
+    new_layout="${layouts[$new_i]}"
+    
+    printf "${cur_layout} -> ${new_layout}"
+    
+    setxkbmap -layout ${new_layout}
+}
 
-print_variant() { [ "${1}" == '' ] && echo "''" || echo "${1}"; }
-printf "layout  : %-8s -> %-8s\n" "${cur_layout}" "${new_layout}"
-printf "variant : %-8s -> %-8s\n" \
-        "$(print_variant ${cur_variant})" \
-        "$(print_variant ${new_variant})"
 
-cmd="setxkbmap -layout ${new_layout}"
-[ "${new_variant}" != '' ] && cmd+=" -variant ${new_variant}"
-#echo "${cmd}"
-eval "${cmd}"
+#
+# Make sure there's access to display
+#
+ensure_display_access()
+{
+    check_display_available && return 0
 
+    # Damn, no display access!
+
+    # Assumption: Lost connection when reattaching to running
+    # remote tmux session (without nested SSH connection).
+    local new_display="$(tmux show-env | sed -n 's/^DISPLAY=//p')"
+    echo "Update DISPLAY: '${DISPLAY}' -> '${new_display}'"
+    export DISPLAY="${new_display}"
+
+    check_display_available && return 0
+
+    # Damn, still no display access!
+
+    echo "$(basename ${0}): Cannot open display '${DISPLAY}'" >&2
+    exit 255
+}
+
+
+#
+# Check whether access to display is available
+#
+check_display_available()
+{
+    # Set test command (optional arguments, otherwise default)
+    local cmd="setxkbmap"
+    [ ${#} -gt 0 ] && cmd="${@}"
+
+    # Runn test command, storing sterr
+    local err=$(setxkbmap 2>&1 >/dev/null)
+
+    # Assumption: no error message if display works, otherwise error message
+    if [ "${err}" == '' ]
+    then
+        return 0
+    elif [ "${err:0:19}" == "Cannot open display" ]
+    then
+        return 255
+    else
+        echo "check_display_available: unexpected error running ${cmd}: ${err}">&2
+        exit 1
+    fi
+}
+
+
+main "${@}"
